---
- name: copy the postgres_exporter systemd service file
  template:
    src: pg_exporter.service.j2
    dest: "/etc/systemd/system/pg_exporter.service"
    owner: root
    group: root
    mode: 0644
  notify: restart postgres_exporter

- name: copy the postgres_exporter env file
  template:
    src: env.j2
    dest: "{{ postgres_exporter_config_install_dir }}/env"
    owner: root
    group: root
    mode: 0640
  notify: restart postgres_exporter

- name: copy postgres_exporter custom metrics file
  template:
    src: metrics.yaml.j2
    dest: "{{ postgres_exporter_config_install_dir }}/metrics.yaml"
    mode: 0644
    owner: root
    group: root
  notify: restart postgres_exporter
  when:
    - postgres_exporter_custom_queries != {}

- name: check status service
  service_facts: