---
- import_tasks: preflight.yml
  become: true
  tags:
    - postgres_exporter_install
    - postgres_exporter_configure
    - postgres_exporter_run

- import_tasks: install.yml
  become: true
  tags:
    - postgres_exporter_install


- import_tasks: configure.yml
  become: true
  tags:
    - postgres_exporter_configure

- name: ensure Postgresql Exporter is enabled on boot
  become: true
  systemd:
    daemon_reload: true
    name: pg_exporter
    enabled: true
    state: started
  when:
    - not ansible_check_mode
  tags:
    - postgres_exporter_run