---
postgres_exporter_dir: '/opt/postgres_exporter'
postgres_exporter_binary_install_dir: "{{ postgres_exporter_dir }}/bin"
postgres_exporter_config_install_dir: "{{ postgres_exporter_dir }}/etc"
postgres_exporter_web_listen_port: 29103
postgres_exporter_web_listen_address: "0.0.0.0:{{ postgres_exporter_web_listen_port }}"
postgres_exporter_service_args:
  log.level: info

postgres_data_source_user: 'postgres_exporter'
postgres_data_source_pass: 'password'
postgres_data_source_uri: '127.0.0.1:5432/postgres?sslmode=disable'
postgres_exclude_database: ''

postgres_exporter_binary_local_dir: ''

# Internal variables.
_postgres_exporter_system_group: 'pg_exporter'
postgres_exporter_system_group: 'pg_exporter'
_postgres_exporter_system_user: "{{ _postgres_exporter_system_group }}"
postgres_exporter_system_user: "{{ _postgres_exporter_system_group }}"

postgres_exporter_env_args:
  data_source_uri: "{{ postgres_data_source_uri }}"
  data_source_user: "{{ postgres_data_source_user }}"
  data_source_pass: "{{ postgres_data_source_pass }}"
  pg_exporter_web_listen_address: "{{ postgres_exporter_web_listen_address }}"
  pg_exporter_auto_discover_databases: true
  pg_exporter_extend_query_path: "{{ postgres_exporter_config_install_dir }}/metrics.yaml"
  pg_exporter_exclude_databases: "{{ postgres_exclude_database }}"

postgres_exporter_custom_queries:
  pg_ip_connection:
    query: "SELECT datname, client_addr, count(*) FROM pg_stat_activity WHERE client_addr IS NOT NULL GROUP BY (client_addr, datname)"
    master: true
    metrics:
      - datname:
          usage: "LABEL"
          description: "Name of database"
      - client_addr:
          usage: "LABEL"
          description: "Client IP address"
      - count:
          usage: "GAUGE"
          description: "Number of connections"
  pg_postmaster:                                                                                           
    query: "SELECT pg_postmaster_start_time as start_time_seconds from pg_postmaster_start_time()"         
    master: true                                                                                           
    metrics: 
      - start_time_seconds:                           
          usage: "GAUGE"                              
          description: "Time at which postmaster started"
  pg_stat_user_tables:      
    query: |             
      SELECT
        current_database() datname,
        schemaname,
        relname,
        seq_scan,
        seq_tup_read,
        idx_scan,
        idx_tup_fetch,
        n_tup_ins,
        n_tup_upd,
        n_tup_del,
        n_tup_hot_upd,
        n_live_tup,
        n_dead_tup,
        n_mod_since_analyze,
        COALESCE(last_vacuum, '1970-01-01Z') as last_vacuum,
        COALESCE(last_autovacuum, '1970-01-01Z') as last_autovacuum,
        COALESCE(last_analyze, '1970-01-01Z') as last_analyze,
        COALESCE(last_autoanalyze, '1970-01-01Z') as last_autoanalyze,
        vacuum_count,
        autovacuum_count,
        analyze_count,
        autoanalyze_count
      FROM 
        pg_stat_user_tables
    metrics:                
      - datname: 
          usage: "LABEL"                              
          description: "Name of current database"                                                          
      - schemaname:         
          usage: "LABEL"                              
          description: "Name of the schema that this table is in"                                          
      - relname:            
          usage: "LABEL"                              
          description: "Name of this table"           
      - seq_scan:           
          usage: "COUNTER"                            
          description: "Number of sequential scans initiated on this table"                                
      - seq_tup_read:       
          usage: "COUNTER"                            
          description: "Number of live rows fetched by sequential scans"                                   
      - idx_scan:           
          usage: "COUNTER"                            
          description: "Number of index scans initiated on this table"                                     
      - idx_tup_fetch:      
          usage: "COUNTER"                            
          description: "Number of live rows fetched by index scans"                                        
      - n_tup_ins:          
          usage: "COUNTER"                            
          description: "Number of rows inserted"                                                           
      - n_tup_upd:          
          usage: "COUNTER"                            
          description: "Number of rows updated"                                                            
      - n_tup_del:          
          usage: "COUNTER"                            
          description: "Number of rows deleted"                                                            
      - n_tup_hot_upd:      
          usage: "COUNTER"                            
          description: "Number of rows HOT updated (i.e., with no separate index update required)"
      - n_live_tup:         
          usage: "GAUGE"                              
          description: "Estimated number of live rows"                                                     
      - n_dead_tup:         
          usage: "GAUGE"                              
          description: "Estimated number of dead rows"                                                     
      - n_mod_since_analyze:                          
          usage: "GAUGE"                              
          description: "Estimated number of rows changed since last analyze"                               
      - last_vacuum:        
          usage: "GAUGE"                              
          description: "Last time at which this table was manually vacuumed (not counting VACUUM FULL)"    
      - last_autovacuum:                              
          usage: "GAUGE"                              
          description: "Last time at which this table was vacuumed by the autovacuum daemon"               
      - last_analyze:       
          usage: "GAUGE"                              
          description: "Last time at which this table was manually analyzed"                               
      - last_autoanalyze:                             
          usage: "GAUGE"                              
          description: "Last time at which this table was analyzed by the autovacuum daemon"               
      - vacuum_count:       
          usage: "COUNTER"                            
          description: "Number of times this table has been manually vacuumed (not counting VACUUM FULL)"  
      - autovacuum_count:                             
          usage: "COUNTER"                            
          description: "Number of times this table has been vacuumed by the autovacuum daemon"             
      - analyze_count:      
          usage: "COUNTER"                            
          description: "Number of times this table has been manually analyzed"                             
      - autoanalyze_count:                            
          usage: "COUNTER"                            
          description: "Number of times this table has been analyzed by the autovacuum daemon"
  pg_statio_user_tables:
    query: "SELECT current_database() datname, schemaname, relname, heap_blks_read, heap_blks_hit, idx_blks_read, idx_blks_hit, toast_blks_read, toast_blks_hit, tidx_blks_read, tidx_blks_hit, pg_total_relation_size(relid), pg_relation_size(relid) FROM pg_statio_user_tables"
    metrics:
      - datname:
          usage: "LABEL"
          description: "Name of current database"
      - schemaname:
          usage: "LABEL"
          description: "Name of the schema that this table is in"
      - relname:
          usage: "LABEL"
          description: "Name of this table"
      - heap_blks_read:
          usage: "COUNTER"
          description: "Number of disk blocks read from this table"
      - heap_blks_hit:
          usage: "COUNTER"
          description: "Number of buffer hits in this table"
      - idx_blks_read:
          usage: "COUNTER"
          description: "Number of disk blocks read from all indexes on this table"
      - idx_blks_hit:
          usage: "COUNTER"
          description: "Number of buffer hits in all indexes on this table"
      - toast_blks_read:
          usage: "COUNTER"
          description: "Number of disk blocks read from this table's TOAST table (if any)"
      - toast_blks_hit:
          usage: "COUNTER"
          description: "Number of buffer hits in this table's TOAST table (if any)"
      - tidx_blks_read:
          usage: "COUNTER"
          description: "Number of disk blocks read from this table's TOAST table indexes (if any)"
      - tidx_blks_hit:
          usage: "COUNTER"
          description: "Number of buffer hits in this table's TOAST table indexes (if any)"               
      - pg_total_relation_size:                       
          usage: "GAUGE"                              
          description: "Total table size"             
      - pg_relation_size:                             
          usage: "GAUGE"                              
          description: "Size of table rows"